from enum import Enum
from typing import Tuple

SCALE: int

class Context: ...

class Layout:
    def __init__(self, context: Context): ...
    def get_pixel_size(self) -> Tuple[int, int]: ...
    def set_alignment(self, alignment: Alignment) -> None: ...
    def set_auto_dir(self, auto_dir: bool) -> None: ...
    def set_ellipsize(self, ellipsize: EllipsizeMode) -> None: ...
    def set_font_description(self, desc: FontDescription) -> None: ...
    def set_height(self, height: int) -> None: ...
    def set_justify(self, justify: bool) -> None: ...
    def set_text(self, text: str, length: int) -> None: ...
    def set_width(self, width: int) -> None: ...
    def set_wrap(self, wrap: WrapMode) -> None: ...

class FontDescription:
    def set_absolute_size(self, size: float) -> None: ...
    def set_family(self, family: str) -> None: ...

class Alignment(Enum):
    LEFT: int
    CENTER: int
    RIGHT: int

class EllipsizeMode(Enum):
    NONE: int
    START: int
    MIDDLE: int
    END: int

class WrapMode(Enum):
    WORD: int
    CHAR: int
    WORD_CHAR: int
