# SPDX-FileCopyrightText: 1999 Red Hat Software
#
# SPDX-License-Identifier: LGPL-2.0-or-later

from enum import Enum
from typing import Tuple

SCALE: int

class Context: ...

class Layout:
    def __init__(self, context: Context): ...
    def get_pixel_size(self) -> Tuple[int, int]: ...
    def set_alignment(self, alignment: Alignment) -> None: ...
    def set_attributes(self, attrs: AttrList) -> None: ...
    def set_auto_dir(self, auto_dir: bool) -> None: ...
    def set_ellipsize(self, ellipsize: EllipsizeMode) -> None: ...
    def set_font_description(self, desc: FontDescription) -> None: ...
    def set_height(self, height: int) -> None: ...
    def set_justify(self, justify: bool) -> None: ...
    def set_line_spacing(self, factor: float) -> None: ...
    def set_text(self, text: str, length: int) -> None: ...
    def set_width(self, width: int) -> None: ...
    def set_wrap(self, wrap: WrapMode) -> None: ...

class Attribute: ...

class AttrList:
    def insert(self, attr: Attribute) -> None: ...

class FontDescription:
    def set_absolute_size(self, size: float) -> None: ...
    def set_family(self, family: str) -> None: ...

class Alignment(Enum):
    LEFT: int
    CENTER: int
    RIGHT: int

class EllipsizeMode(Enum):
    NONE: int
    START: int
    MIDDLE: int
    END: int

class WrapMode(Enum):
    WORD: int
    CHAR: int
    WORD_CHAR: int

def attr_letter_spacing_new(letter_spacing: int) -> Attribute: ...
