#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2022 BigBlueButton Inc. and by respective authors
#
# SPDX-License-Identifier: GPL-3.0-or-later

import bbb_presentation_video

bbb_presentation_video.main()
