from typing import Optional, Tuple

import cairo

class Document:
    @classmethod
    def new_from_file(cls, uri: str, password: Optional[str] = None) -> Document: ...
    def get_n_pages(self) -> int: ...
    def get_page(self, index: int) -> Optional[Page]: ...

class Page:
    def get_size(self) -> Tuple[float, float]: ...
    def render(self, cairo: cairo.Context) -> None: ...
