from typing import Union

class Pixbuf:
    @classmethod
    def new_from_file(cls, filename: Union[str, bytes]) -> Pixbuf: ...
    def get_height(self) -> int: ...
    def get_width(self) -> int: ...
