import cairo
from gi.repository import Pango

def context_set_font_options(
    context: Pango.Context, options: cairo.FontOptions
) -> None: ...
def create_context(cr: cairo.Context) -> Pango.Context: ...
def show_layout(cr: cairo.Context, layout: Pango.Layout) -> None: ...
